name: Setup Project
description: 'Setup a nodejs project with npm dependencies and cache.'
inputs:
  projectDirectory:
    description: 'The directory of the project to setup.'
    required: true
  nodeVersion:
    description: 'The version of node to use.'
    required: true
  registry-url:
    description: 'The registry to use for npm.'
    required: false
  npmToken:
    description: 'The npm token to use for authentication.'
    required: false
runs:
   using: 'composite'
   steps:
     - name: Use Node ${{inputs.nodeVersion}}
       uses: actions/setup-node@v4
       with:
         node-version: ${{inputs.nodeVersion}}
         cache: npm
         cache-dependency-path: ./package-lock.json
        
     - name: Install project dependencies
       run: npm ci
       shell: bash
       working-directory: ${{inputs.projectDirectory}}