name: Set up Test
description: 'Run test'
inputs:
  projectDirectory:
    description: 'The directory of the project to set up'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ${{ inputs.projectDirectory }}/reports/test-results.xml
        check_name: "Test Results - ${{ input.project }}"
      # check_run: true
      # working-directory: ${{ inputs.projectDirectory }}