name: Set up Test
description: 'Run test'
inputs:
  projectDirectory:
    description: 'The directory of the project to set up'
    required: true
  nodeVersion:
    description: 'The Node.js version to use'
    required: true
    default: '18.x'
runs:
  using: 'composite'
  steps:
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          ${{ inputs.projectDirectory }}/reports/test-results.xml
      check_run: true
      working-directory: ${{ inputs.projectDirectory }}