name: Set up Test
description: 'Run test'
inputs:
  projectDirectory:
    description: 'The directory of the project to set up'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install jest-junit temporarily
      run: npm install --no-save jest-junit
      working-directory: ${{ inputs.projectDirectory }}
      shell: bash

    - name: Unit test
      run: |
         npm run --if-present test:cov -- --reporters=default --reporters=jest-junit || echo "test script not found, skipping."
      working-directory: ${{inputs.projectDirectory}}
      env:
          JEST_JUNIT_OUTPUT_DIR: ${{ inputs.projectDirectory }}/reports
          JEST_JUNIT_OUTPUT_NAME: test-results.xml
      shell: bash
    
    - name: List directory structure after npm install
      run: ls -R
      working-directory: ${{ inputs.projectDirectory }}
      shell: bash

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ${{ inputs.projectDirectory }}/reports/test-results.xml
        check_name: "Test Results - ${{ inputs.project }}"
        comment_mode: off
        # hiding_comments: all
      # check_run: true
      # working-directory: ${{ inputs.projectDirectory }}