name: Setup Project
description: 'Setup a nodejs project with npm dependencies and cache.'
inputs:
  project-directory:
    description: 'The directory of the project to setup.'
    required: true
  node-version:
    description: 'The version of node to use.'
    required: true
  registry-url:
    description: 'The registry to use for npm.'
    required: false
  npmToken:
    description: 'The npm token to use for authentication.'
    required: false
runs:
   using: 'composite'
   steps:
     - name: Use Node ${{inputs.node-version}}
       uses: actions/setup-node@v4
       with:
         node-version: ${{inputs.node-version}}
         cache: npm
         cache-dependency-path: ${{inputs.project-directory}}/package-lock.json
        
    # - name: Configure npm for private projects
     - name: Install project dependencies
        run: npm ci
        shell: bash
        working-directory: ${{inputs.project-directory}}