name: CI
on:
 push:
    branches:
        - main
 pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  changes:
    name: Identify file changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      checks: write
    outputs:
      paths: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            date-helpers:
              - 'packages/date-helpers/**'
            hello-world-util:
              - 'packages/hello-world-util/**'
            feature-flags:
              - 'packages/feature-flags/**'
            string-utils:
              - 'packages/string-utils/**'
            task-queue-manager:
              - 'packages/task-queue-manager/**'
            nestjs-startup-app:
              - 'starters/nestjs-startup-app/**'
  sonar: 
    name: SonarQube Scan
    needs: changes
    strategy:
      matrix:
        include:
          - filter: date-helpers
            projectDirectory: packages/date-helpers
            nodeVersion: 'lts/*'
          - filter: hello-world-util
            projectDirectory: packages/hello-world-util
            nodeVersion: 'lts/*'
          - filter: feature-flags
            projectDirectory: packages/feature-flags
            nodeVersion: 'lts/*'
          - filter: string-utils
            projectDirectory: packages/string-utils
            nodeVersion: 'lts/*'
          - filter: task-queue-manager
            projectDirectory: packages/task-queue-manager
            nodeVersion: 'lts/*'
          - filter: nestjs-startup-app
            projectDirectory: starters/nestjs-startup-app
            nodeVersion: 'lts/*'
    uses: ./.github/workflows/workflow-sonarcloud-workspaces.yml
    with:
      projectDirectory: ${{ matrix.projectDirectory }}
      nodeVersion: ${{ matrix.nodeVersion }}
      registry-url: 'https://registry.npmjs.org'
      filters: ${{ needs.changes.outputs.paths }}
      filter: ${{ matrix.filter }}
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      # npmToken: ${{ secrets.NPM_TOKEN }}
