name: Dry Run Release
on:
  pull_request:
    branches:
        - feature/*
    types: [opened, synchronize, reopened]
  push:
    branches:
        - feature/*
jobs:
  dry-run-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: lts/*

      - name: Install release-please
        run: npm install -g release-please

      - name: Run release-please (dry-run mode)
        # if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
            echo "Repository url is: ${{ github.repository }}"
            release-please release-pr --token=${{ secrets.PAT }} --repo-url=https://github.com/${{ github.repository }} --dry-run
            release-please manifest-pr --token=${{ secrets.PAT }} --repo-url=https://github.com/${{ github.repository }} --dry-run