name: release
on:
    push:
      branches:
        - main
permissions:
  contents: write
  pull-requests: write
jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: googleapis/release-please-action@v4
          id: release
          with:
            token: ${{secrets.GITHUB_TOKEN}}
            # release-type: node
            # config-file: release-please-config.json
            # manifest-file: .release-please-manifest.json
            # path: | 
            #     packages/hello-world-util
        # The logic below handles the npm publication:
        - name: Checkout 
          if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
          uses: actions/checkout@v4
          # these if statements ensure that a publication only occurs when
          # a new release is created:
        - name: Setup Node.js
          if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
            registry-url: 'https://registry.npmjs.org'
        
        - name: Install dependencies
          if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
          run: npm install
        
        - name: Publish
          if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
          run: npx lerna publish from-package --no-push --no-private --yes
          env:
            NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
            # if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}