name: Relase
on:
 push:
    branches:
        - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
        #   command: manifest
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
        #   default-branch: main

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/some-build-artifact.zip

      # The logic handles npm publication
      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}        
        uses: actions/checkout@v4

      - name: Print release outputs
        run: |
          echo "release_created: ${{ steps.release.outputs }}"
    
      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: node@latest
          registry-url: https://registry.npmjs.org/
      - name: Build Packages
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm install 
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          run: npx lerna publish from-package --no-push --no-private --yes
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    