name: release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug release output
        run: "echo 'Paths released: ${{ steps.release.outputs.paths_released }}'"

  publish-packages:
    needs: release-please
    if: ${{ needs.release-please.outputs.paths_released != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectDirectory: ${{ fromJson(needs.release-please.outputs.paths_released) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug release output
        run: "echo 'Paths released: ${{ needs.release-please.outputs.paths_released }}'"

      - name: Set up Project
        uses: ./.github/actions/setup-node-project
        with:
          projectDirectory: ${{ matrix.projectDirectory }}
          nodeVersion: lts/*
          registry-url: 'https://registry.npmjs.org'
          npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Build packages for ${{ matrix.projectDirectory }}
        run: npm run build
        working-directory: ${{ matrix.projectDirectory }}

      - name: Print directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory structure after build:"
          ls -R
        working-directory: ${{ matrix.projectDirectory }}
      
      - name: Publish
        working-directory: ${{ matrix.projectDirectory }}
        # run: npx publish from-package --contents dist --no-push --no-private --yes
        run: npm publish --contents dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}