name: release
on:
    push:
      branches:
        - main
permissions:
  contents: write
  pull-requests: write
jobs:
    release-please:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - projectDirectory: packages/hello-world-util
              artifactName: pkg-hello-world-util
              nodeVersion: 'lts/*'
      steps:
        - uses: googleapis/release-please-action@v4
          id: release
          with:
            token: ${{secrets.GITHUB_TOKEN}}
            # release-type: node
            # config-file: release-please-config.json
            # manifest-file: .release-please-manifest.json
            # path: | 
            #     packages/hello-world-util
        # The logic below handles the npm publication:
          #info: The below Setup output-key step is used to store the output of the release-please-action since we are using a matrix strategy
          # we need to get the projectDirectory name dynamically while publishing the package & we cannot do the same while publishing packages
          # Setting the same in env variable & checking in preeceding steps using the .set-output-key step would let access dynamically.
        - name: Setup output-key
          id: set-output-key
          run: |
             echo "release_created_output=steps.release.outputs['${{ matrix.projectDirectory }}--release_created']" >> $GITHUB_ENV 

        - name: Checkout 
          # if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
          if: ${{ steps.set-output-key.outputs.release_created_output == 'true'}}
          uses: actions/checkout@v4
          # these if statements ensure that a publication only occurs when
          # a new release is created:
        # - name: Setup Node.js
        #   if: ${{ steps.set-output-key.outputs.release_created_output == 'true'}}
        #   # if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
        #   uses: actions/setup-node@v4
        #   with:
        #     node-version: lts/*
        #     registry-url: 'https://registry.npmjs.org'
        
        # - name: Install dependencies
        #   if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
        #   run: npm install

        - name: Set up Project
          if: ${{ steps.set-output-key.outputs.release_created_output == 'true'}}
          uses: ./.github/actions/setup-node-project
          with:
            projectDirectory: ${{ matrix.projectDirectory }}
            nodeVersion: lts/*
            registry-url: 'https://registry.npmjs.org'
            npmToken: ${{ secrets.NPM_TOKEN }}

        - name: Build packages
          run: npx lerna run build
        
        - name: Publish
          # if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
          if: ${{ steps.set-output-key.outputs.release_created_output == 'true'}}
          # run: npx lerna publish from-package --no-push --no-private --yes
          run: npx lerna publish from-package --contents dist --no-push --no-private --yes

          env:
            NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}