name: Release
on:
 push:
    branches:
        - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
        #   command: manifest
          release-type: node
        #   path: packages/hello-world-util
          config-file: release-please-configtest.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
        #   default-branch: main

      # The logic handles npm publication
      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}        
        uses: actions/checkout@v4

      - name: Print release outputs
        continue-on-error: true
        run: |
          echo "release_created: ${{ toJson(steps.release.outputs) }}"
    
      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          
      - name: Build Packages
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm install 
          
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: npx lerna publish from-package --no-push --no-private --yes
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    
      - name: Generate artifacts
        run: |
            mkdir -p artifact
            zip -r ./artifact/package-artifact.zip . -i ./packages/hello-world-util/dist

      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs['packages/hello-world-util--release_created'] }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs['packages/hello-world-util--tag_name'] }} ./artifact/package-artifact.zip
    